### ISSUE TITLE
New releases of fzf include "v" prefix

### ISSUE THREAD

**Issue by HipsterBrown** [kompiro/asdf-fzf#2]
The latest release of fzf ([v0.54.0](https://github.com/junegunn/fzf/releases/tag/v0.54.0)) documents a change in the tagging scheme to include the "v" prefix. I've updated my local version of this plugin to use that new naming scheme for the download_url since I generally stay on the latest releases. I'm not sure how to conditionally apply this as a PR to this project without breaking backwards compat.

**Comment by stherold** [comment]
I think this is related to my comment https://github.com/kompiro/asdf-fzf/pull/3#issuecomment-2326668436

**Comment by ghost** [comment]
This seems to be fixed now. It only requires updating the plugin via `mise plugin up fzf`/`asdf plugin update fzf`

**Comment by kompiro** [comment]
Yes, Thanks
